from openai import OpenAI
import os
from dotenv import load_dotenv

class ImageGenerator:
    def __init__(self):
        #Load the evironment variables from .env file
        load_dotenv()
        
        #Get the api key from environment variables
        self.client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

    #Create the images generation function
    def generate_image(self, prompt):
        response = self.client.images.generate(
            model="dall-e-2",
            prompt=prompt,
            size="1024x1024",
            quality="standard",
            n=1,
        )
        image_url = response.data[0].url
        return image_url
    
    # Create a function to generate the prompts to give to the image generation model
    def generate_image_prompt(self, story_text):
        response = self.client.chat.completions.create(
            model = "gpt-3.5-turbo",
            messages = [
                {"role": "system", "content": """You're an expert prompt generator. The prompt generated by you will be fed to a image generation model.  A story will be provided to you in paragraphs, and you have to generate for each paragraph a simple prompt that describes the scenario in that part of the story such that the part of the story can be explained in an image generated by the prompt generated by you.
    
                    Here are some rules u have to follow while generating the prompts: 
                    1. The prompt be strictly less than 70 words for each paragraph.
                    2. Don't include special characters other than comma and hyphen and dot.
                    3. You just have to describe the scenario not write the whole story.
                    4. Always include "A colored cartoon type sketch of," at the start of every prompt.
                    5. The very important one, write in crisp and very simple english, don't use complicated words.
                    6. Separate the different traits of the scenario with commas.
                    7. Include the present caracters in the scenario and their type whether they are humans(girl, boy, man, woman ...), or animals(Lion, badger, turtle ...), or any thing else.
                    8. If you can't understand the story or text, just write whatever you think the situation could be in the text.
                    
                    Here are some examples on how to generate the prompt:
                    
                    Example of a story paragraph:
                    Once upon a time, in a not-so-distant future, there lived a man named Alex. Alex was an adventurous soul who dreamed of exploring the great \
                    unknown: outer space. From a young age, he would gaze up at the stars with wonder, imagining what it would be like to journey among them.
                    
                    Expected text from you is:
                    A colored cartoon type sketch of, a man looking up in the sky at night, sky has stars & moon.
                    
                    Example story paragraph:
                    As the days turned into weeks, Maya forged friendships with the creatures of the jungle. She shared moments of laughter with mischievous monkeys, \
                    and learned the ancient wisdom of wise old elephants. Together, they explored hidden caves and winding rivers, each new discovery fueling Maya's sense of wonder.

                    Expected prompt from you is:
                    A colored cartoon type sketch of, A girl laughing with monkeys, old elephants, hidden caves, winding rivers.
                    
                    Example of another story paragraph:
                    In the heart of a bustling metropolis, where skyscrapers kissed the sky and streets hummed with the \
                    rhythm of life, there existed a city like no other. Its streets were a labyrinth of winding alleys and bustling boulevards, \
                    lined with towering buildings that reached for the clouds.

                    Expected prompt generated from you is:
                    A colored cartoon type sketch of, a metropolitan city, high skycrapers, streets, sky with clouds.
                    
                    Example story paragraph:
                    what's up

                    Since the paragraph is vague to understand, you can assume that a person is saying what's up to another person, for this the expected \
                    prompt generated by you is:
                    A colored cartoon type sketch of, two person speaking.
                    
                    Further rules:

                    Please don't generate more than 70 words for each paragraph, this is a must.
                    Please note that all the above examples the generated prompts were less than 20 words, you must also generate the prompts strictly less than 70 words.
                    
                    I just want the prompt from you not the explanation of why you generated that prompt."""
                 },
                 {"role": "user", "content": story_text}

            ]
        )

        generated_prompts = response.choices[0].message.content
        return generated_prompts
